### ISSUE TITLE
您好，非常好的作品，值得我们学习，我在复现的时候，运行sh scripts/train_lora.sh，报错AttributeError: 'GraphEditForCausalLM' object has no attribute 'pretraining_tp'

### ISSUE THREAD

**Issue by zjj1333** [HKUDS/GraphEdit#14]
0%|                                                                                                                                                 | 0/6344 [00:00<?, ?it/s]Traceback (most recent call last):
  File "graphedit/train/train_lora.py", line 259, in <module>
    train()
  File "graphedit/train/train_lora.py", line 234, in train
    trainer.train()
  File "/home/bfs/STUDY2-2024/GraphEdit-main/LLM/graphedit/train/GraphEdit_trainer.py", line 88, in train
    return inner_training_loop(
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/transformers/trainer.py", line 3318, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/transformers/trainer.py", line 3363, in compute_loss
    outputs = model(**inputs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1807, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1208, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/peft/peft_model.py", line 1577, in forward
    return self.base_model(
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1208, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/bfs/STUDY2-2024/GraphEdit-main/LLM/graphedit/model/GraphEdit.py", line 194, in forward
    if self.pretraining_tp  > 1:
  File "/home/bfs/miniconda3/envs/GraphEdit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GraphEditForCausalLM' object has no attribute 'pretraining_tp'

**Comment by zjj1333** [comment]
已经解决了，在模型初始化的时候添加self.pretraining_tp = config.pretraining_tp if hasattr(config, 'pretraining_tp') else 1  # 默认值设为 1


class GraphEditForCausalLM(LlamaForCausalLM):
    config_class = GraphEditConfig

    def __init__(self, config):
        super(GraphEditForCausalLM, self).__init__(config)
        self.pretraining_tp = config.pretraining_tp if hasattr(config, 'pretraining_tp') else 1  # 默认值设为 1

    
    def get_model(self):
        return self.model
