### ISSUE TITLE
请问怎么使用除了vicuna的模型进行微调？

### ISSUE THREAD

**Issue by guanfaqian** [HKUDS/GraphEdit#8]
您好，您的代码给了train_lora.sh的代码，仅能在vicuna微调。然后我看到有train_baichuan.py文件。但是我写了一个ttrain_baichuan.sh的文件却发现multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/home/gfq/anaconda3/envs/edit/lib/python3.10/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
TypeError: apply_prompt_template() takes from 1 to 2 positional arguments but 3 were given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/gfq/code/GraphEdit/LLM/graphedit/train/train_baichuan.py", line 337, in
train()
File "/home/gfq/code/GraphEdit/LLM/graphedit/train/train_baichuan.py", line 321, in train
data_module = make_supervised_data_module(
File "/home/gfq/code/GraphEdit/LLM/graphedit/train/train_baichuan.py", line 274, in make_supervised_data_module
train_dataset = dataset_cls(train_raw_data, tokenizer=tokenizer)
File "/home/gfq/code/GraphEdit/LLM/graphedit/train/train_baichuan.py", line 194, in init
data_dict = preprocess(sources, tokenizer, systems=systems)
File "/home/gfq/code/GraphEdit/LLM/graphedit/train/train_baichuan.py", line 167, in preprocess
).get()
File "/home/gfq/anaconda3/envs/edit/lib/python3.10/multiprocessing/pool.py", line 774, in get
raise self._value
TypeError: apply_prompt_template() takes from 1 to 2 positional arguments but 3 were given
[2024-05-24 17:17:11,220] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 593226

这要怎么调呢？

我想在baichuan、longchat、fastchat这种模型下进行微调。您能指导一下吗？

**Comment by LarFii** [comment]
感谢您的关注！我们的训练脚本是基于[FastChat](https://github.com/lm-sys/FastChat)修改的，主要改动在train_lora.py中，其余模型的微调需要参考train_lora.py进行修改。

**Comment by guanfaqian** [comment]
好像RevGAT代码也不能运行？

**Comment by LarFii** [comment]
目前模型GNN模型选用的是GCN，其余GNN模型需要做相应修改。
